
service: hacker-news-serverless-api

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 256
  timeout: 20


functions:
  cron:
    handler: handler.cron
    events:
      - schedule: rate(30 minutes)

