
service: hacker-news-serverless-api

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-west-2
  memorySize: 512
  timeout: 60

  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "s3:ListBucket"
       Resource:
         Fn::Join:
           - ""
           - - "arn:aws:s3:::"
             - Ref: ServerlessDeploymentBucket
    -  Effect: "Allow"
       Action:
         - "s3:PutObject"
       Resource:
         Fn::Join:
           - ""
           - - "arn:aws:s3:::"
             - Ref: ServerlessDeploymentBucket
             - "/*"
    -  Effect: "Allow"
       Action:
         - "s3:*"
       Resource: "arn:aws:s3:::serverless-api.hackernewsmobile.com/*"



functions:
  cron:
    handler: handler.cron
    events:
      - schedule: rate(30 minutes)
